# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: van.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='van.proto',
  package='',
  syntax='proto3',
  serialized_options=b'Z\001.',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tvan.proto\"#\n\x07request\x12\x18\n\x10instruments_name\x18\x01 \x01(\t\"\x1a\n\x08response\x12\x0e\n\x06result\x18\x01 \x01(\t\"q\n\rsweep_request\x12\x12\n\nstart_volt\x18\x01 \x01(\x02\x12\x11\n\tvolt_step\x18\x02 \x01(\x02\x12\x10\n\x08\x65nd_volt\x18\x03 \x01(\x02\x12\x14\n\x0c\x63urrent_cmpl\x18\x04 \x01(\x02\x12\x11\n\tmes_speed\x18\x05 \x01(\x02\x32k\n\x15InstrumentsController\x12$\n\x0b\x43loseOutput\x12\x08.request\x1a\t.response\"\x00\x12,\n\x0bIVSweepMode\x12\x0e.sweep_request\x1a\t.response\"\x00\x30\x01\x42\x03Z\x01.b\x06proto3'
)




_REQUEST = _descriptor.Descriptor(
  name='request',
  full_name='request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='instruments_name', full_name='request.instruments_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=48,
)


_RESPONSE = _descriptor.Descriptor(
  name='response',
  full_name='response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='response.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=76,
)


_SWEEP_REQUEST = _descriptor.Descriptor(
  name='sweep_request',
  full_name='sweep_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_volt', full_name='sweep_request.start_volt', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='volt_step', full_name='sweep_request.volt_step', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end_volt', full_name='sweep_request.end_volt', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='current_cmpl', full_name='sweep_request.current_cmpl', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mes_speed', full_name='sweep_request.mes_speed', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=191,
)

DESCRIPTOR.message_types_by_name['request'] = _REQUEST
DESCRIPTOR.message_types_by_name['response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['sweep_request'] = _SWEEP_REQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

request = _reflection.GeneratedProtocolMessageType('request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'van_pb2'
  # @@protoc_insertion_point(class_scope:request)
  })
_sym_db.RegisterMessage(request)

response = _reflection.GeneratedProtocolMessageType('response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'van_pb2'
  # @@protoc_insertion_point(class_scope:response)
  })
_sym_db.RegisterMessage(response)

sweep_request = _reflection.GeneratedProtocolMessageType('sweep_request', (_message.Message,), {
  'DESCRIPTOR' : _SWEEP_REQUEST,
  '__module__' : 'van_pb2'
  # @@protoc_insertion_point(class_scope:sweep_request)
  })
_sym_db.RegisterMessage(sweep_request)


DESCRIPTOR._options = None

_INSTRUMENTSCONTROLLER = _descriptor.ServiceDescriptor(
  name='InstrumentsController',
  full_name='InstrumentsController',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=193,
  serialized_end=300,
  methods=[
  _descriptor.MethodDescriptor(
    name='CloseOutput',
    full_name='InstrumentsController.CloseOutput',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='IVSweepMode',
    full_name='InstrumentsController.IVSweepMode',
    index=1,
    containing_service=None,
    input_type=_SWEEP_REQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_INSTRUMENTSCONTROLLER)

DESCRIPTOR.services_by_name['InstrumentsController'] = _INSTRUMENTSCONTROLLER

# @@protoc_insertion_point(module_scope)
